### ISSUE TITLE
Dependency hell!

### ISSUE THREAD

**Issue by vergissberlin** [ddluc/grunt-backstop#8]
**Hi!**

you made a grunt task with dependencies to **gulp** and **bower**?
What were the reasons for these decisions?

kind regards
André

**Comment by andypattenden** [comment]
Backstop used to have dependencies on these but they have been removed since v1.1. There is an old pull request, #7 which removed the dependencies from this package but it hasn't been accepted yet.

**Comment by ddluc** [comment]
My apologies, looks like I'm way overdue on that pull request. Thanks for the ping.
